version: "3.8"
services:
    django:
        build: ./backend
        command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - ./backend:/app/backend
        ports:
            - "8000:8000"
    react:
        build: ./frontend
        stdin_open: true
        tty: true
        depends_on:
            - django
        command: ["npm", "start"]
        volumes:
            - ./frontend:/app/frontend/
            - ./frontend/node-modules:/app/frontend/node_modules/
        ports:
            - "3000:3000"
volumes:
    node-modules:
